# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToolbarRight(object):
    def setupUi(self, ToolbarRight):
        ToolbarRight.setObjectName("ToolbarRight")
        ToolbarRight.resize(119, 178)
        ToolbarRight.setStyleSheet("background-color : rgb(66, 66, 66)")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ToolbarRight)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_Previous = QtWidgets.QPushButton(ToolbarRight)
        self.pushButton_Previous.setStyleSheet("background-color : rgb(235, 235, 235)")
        self.pushButton_Previous.setObjectName("pushButton_Previous")
        self.verticalLayout.addWidget(self.pushButton_Previous)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_Go = QtWidgets.QPushButton(ToolbarRight)
        self.pushButton_Go.setAutoFillBackground(False)
        self.pushButton_Go.setStyleSheet("background-color : rgb(0, 143, 0)")
        self.pushButton_Go.setObjectName("pushButton_Go")
        self.verticalLayout.addWidget(self.pushButton_Go)
        self.pushButton_Stop = QtWidgets.QPushButton(ToolbarRight)
        self.pushButton_Stop.setAutoFillBackground(False)
        self.pushButton_Stop.setStyleSheet("background : rgb(255, 0,0)")
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.verticalLayout.addWidget(self.pushButton_Stop)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ToolbarRight)
        QtCore.QMetaObject.connectSlotsByName(ToolbarRight)

    def retranslateUi(self, ToolbarRight):
        _translate = QtCore.QCoreApplication.translate
        ToolbarRight.setWindowTitle(_translate("ToolbarRight", "Toolbar_Left"))
        self.pushButton_Previous.setText(_translate("ToolbarRight", "Previous"))
        self.pushButton_Go.setText(_translate("ToolbarRight", "Go"))
        self.pushButton_Stop.setText(_translate("ToolbarRight", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ToolbarRight = QtWidgets.QWidget()
    ui = Ui_ToolbarRight()
    ui.setupUi(ToolbarRight)
    ToolbarRight.show()
    sys.exit(app.exec_())
